[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "task_tracker_cli"
version = "0.0.1"
requires-python = ">= 3.11"

[project.scripts]
task = "task_tracker_cli:main"
